name: Build and Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: node-cache
        with:
          path: node_modules
          key: node-cache-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
        if: steps.node-cache.outputs.cache-hit != 'true'
      - run: npm run lint
      - run: npm run pack
      # TODO: - run: npm test
